### ISSUE TITLE
amazing

### ISSUE THREAD

**Issue by mesqueeb** [nanoutils/nanoutils#111]
Did you write all these functions on your own?
It's just really amazing. They all include tests as well?
AND ARE NANO SIZE?!?
I assume they support tree-shaking with webpack AND rollup?
Great stuff man.

**Comment by Kelin2025** [comment]
It's not only my work and I want to say thanks to @Beraliv and @BabkinAleksandr for help ^^

Yep, tests are done but there are still no types. Btw, since it's _Ramda-compatible_, Ramda's typings can be used here 🤔 

Yep, you can check size difference for each method [here](https://github.com/nanoutils/nanoutils/blob/master/SIZES.md)

Tree-shaking doesn't work with `export { default as smth }` but we wrote a [babel-plugin-nanoutils](https://github.com/nanoutils/babel-plugin-nanoutils) (like ramda and lodash plugins) that will import only used methods
